// <auto-generated>
// This file should only contain assembly level attributes.
// Do not add any class or struct definitions as it may disable the ability of the tool to
// update the file.
// </auto-generated>

using System;

using System.Runtime.CompilerServices;
[assembly: InternalsVisibleTo("Similarity.Tests")]
[assembly: InternalsVisibleTo("Similarity.Explorables")]
